version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    volumes:
      - ./path/to/service-account-key.json:/app/key.json:ro
    networks:
      - appdirect-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - appdirect-network

networks:
  appdirect-network:
    driver: bridge
